// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class BookingCuongCla
{
    public int BookingCuongClaid { get; set; }

    public int CustomerId { get; set; }

    public int VehicleId { get; set; }

    public int StationId { get; set; }

    public DateTime BookingDate { get; set; }

    public DateTime PlannedPickUpDate { get; set; }

    public DateTime PlannedReturnDate { get; set; }

    public DateTime? ActualPickUpDate { get; set; }

    public DateTime? ActualReturnDate { get; set; }

    public string Status { get; set; }

    public decimal TotalCost { get; set; }

    public decimal DepositAmount { get; set; }

    public bool IsDepositPaid { get; set; }

    public string Notes { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual SystemUserAccount CreatedByNavigation { get; set; }

    public virtual CustomerManagementConglt Customer { get; set; }

    public virtual ICollection<PaymentCuongCla> PaymentCuongClas { get; set; } = new List<PaymentCuongCla>();

    public virtual ICollection<RentalTransactionsKhanhLq> RentalTransactionsKhanhLqs { get; set; } = new List<RentalTransactionsKhanhLq>();

    public virtual StationHuyNd Station { get; set; }

    public virtual VehicleHaLth Vehicle { get; set; }
}