// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class CustomerManagementConglt
{
    public int CustomerManagementCongltId { get; set; }

    public int UserAccountId { get; set; }

    public int ViolationCongltId { get; set; }

    public string ActionType { get; set; }

    public DateTime ActionDate { get; set; }

    public string PreviousStatus { get; set; }

    public string NewStatus { get; set; }

    public string Reason { get; set; }

    public string Notes { get; set; }

    public string Complaint { get; set; }

    public int? RiskLevel { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string IdcardNumber { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public string Address { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public string Status { get; set; }

    public int? TotalBookings { get; set; }

    public decimal? TotalSpent { get; set; }

    public decimal? AverageRating { get; set; }

    public virtual ICollection<BookingCuongCla> BookingCuongClas { get; set; } = new List<BookingCuongCla>();

    public virtual ICollection<RentalTransactionsKhanhLq> RentalTransactionsKhanhLqs { get; set; } = new List<RentalTransactionsKhanhLq>();

    public virtual SystemUserAccount UserAccount { get; set; }

    public virtual ViolationRecordConglt ViolationConglt { get; set; }
}