// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class PaymentCuongCla
{
    public int PaymentCuongClaid { get; set; }

    public int BookingId { get; set; }

    public DateTime PaymentDate { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public bool IsDeposit { get; set; }

    public string Notes { get; set; }

    public decimal? DepositReturnAmount { get; set; }

    public int? ProcessedBy { get; set; }

    public virtual BookingCuongCla Booking { get; set; }

    public virtual SystemUserAccount ProcessedByNavigation { get; set; }
}