// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class PricingPhatNt
{
    public int PricingPhatNtid { get; set; }

    public string VehicleType { get; set; }

    public decimal BasePrice { get; set; }

    public decimal PeakHourMultiplier { get; set; }

    public decimal OffPeakMultiplier { get; set; }

    public TimeOnly PeakStartTime { get; set; }

    public TimeOnly PeakEndTime { get; set; }

    public DateOnly EffectiveDate { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<VehicleManagementPhatNt> VehicleManagementPhatNts { get; set; } = new List<VehicleManagementPhatNt>();
}