// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class RentalTransactionsKhanhLq
{
    public int RentalTransactionsKhanhLqid { get; set; }

    public int BookingId { get; set; }

    public int UserAccountId { get; set; }

    public int CustomerId { get; set; }

    public int VehicleId { get; set; }

    public string TransactionType { get; set; }

    public DateTime TransactionDate { get; set; }

    public int BatteryLevel { get; set; }

    public int Mileage { get; set; }

    public string VehicleCondition { get; set; }

    public bool IsContractSigned { get; set; }

    public string SignaturePath { get; set; }

    public string Notes { get; set; }

    public string Status { get; set; }

    public virtual BookingCuongCla Booking { get; set; }

    public virtual CustomerManagementConglt Customer { get; set; }

    public virtual ICollection<TransactionChecklistResultsKhanhLq> TransactionChecklistResultsKhanhLqs { get; set; } = new List<TransactionChecklistResultsKhanhLq>();

    public virtual SystemUserAccount UserAccount { get; set; }

    public virtual VehicleHaLth Vehicle { get; set; }
}