// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class StationOperationsHuyNd
{
    public int StationOperationsHuyNdid { get; set; }

    public int StationId { get; set; }

    public int UserAccountId { get; set; }

    public DateOnly OperationDate { get; set; }

    public int TotalTransactions { get; set; }

    public int SuccessfulTransactions { get; set; }

    public decimal? CustomerSatisfactionRating { get; set; }

    public int? IssuesReported { get; set; }

    public decimal? Revenue { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual StationHuyNd Station { get; set; }

    public virtual SystemUserAccount UserAccount { get; set; }
}