// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class StationHuyNd
{
    public int StationHuyNdid { get; set; }

    public string StationName { get; set; }

    public string Address { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public TimeOnly OpeningTime { get; set; }

    public TimeOnly ClosingTime { get; set; }

    public bool IsActive { get; set; }

    public int Capacity { get; set; }

    public string ContactPhone { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual ICollection<BookingCuongCla> BookingCuongClas { get; set; } = new List<BookingCuongCla>();

    public virtual ICollection<StationOperationsHuyNd> StationOperationsHuyNds { get; set; } = new List<StationOperationsHuyNd>();

    public virtual ICollection<VehicleHaLth> VehicleHaLths { get; set; } = new List<VehicleHaLth>();

    public virtual ICollection<VehicleManagementPhatNt> VehicleManagementPhatNtNewStations { get; set; } = new List<VehicleManagementPhatNt>();

    public virtual ICollection<VehicleManagementPhatNt> VehicleManagementPhatNtPreviousStations { get; set; } = new List<VehicleManagementPhatNt>();
}