// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class SystemUserAccount
{
    public int UserAccountId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string EmployeeCode { get; set; }

    public int RoleId { get; set; }

    public string RequestCode { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ApplicationCode { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<BookingCuongCla> BookingCuongClas { get; set; } = new List<BookingCuongCla>();

    public virtual ICollection<CustomerManagementConglt> CustomerManagementConglts { get; set; } = new List<CustomerManagementConglt>();

    public virtual ICollection<PaymentCuongCla> PaymentCuongClas { get; set; } = new List<PaymentCuongCla>();

    public virtual ICollection<RentalTransactionsKhanhLq> RentalTransactionsKhanhLqs { get; set; } = new List<RentalTransactionsKhanhLq>();

    public virtual ICollection<StationOperationsHuyNd> StationOperationsHuyNds { get; set; } = new List<StationOperationsHuyNd>();

    public virtual ICollection<TransactionChecklistResultsKhanhLq> TransactionChecklistResultsKhanhLqs { get; set; } = new List<TransactionChecklistResultsKhanhLq>();

    public virtual ICollection<VehicleMaintenanceHistoryHaLth> VehicleMaintenanceHistoryHaLths { get; set; } = new List<VehicleMaintenanceHistoryHaLth>();
}