// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class TransactionChecklistResultsKhanhLq
{
    public int TransactionChecklistResultsKhanhLqid { get; set; }

    public int TransactionId { get; set; }

    public bool CheckResult { get; set; }

    public string Notes { get; set; }

    public int CheckedBy { get; set; }

    public DateTime? CheckedDate { get; set; }

    public virtual SystemUserAccount CheckedByNavigation { get; set; }

    public virtual RentalTransactionsKhanhLq Transaction { get; set; }
}