// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class VehicleManagementPhatNt
{
    public int VehicleManagementPhatNtid { get; set; }

    public int VehicleId { get; set; }

    public string ActionType { get; set; }

    public DateTime ActionDate { get; set; }

    public int? PreviousStationId { get; set; }

    public int? NewStationId { get; set; }

    public string PreviousStatus { get; set; }

    public string NewStatus { get; set; }

    public int? BatteryLevelBefore { get; set; }

    public int? BatteryLevelAfter { get; set; }

    public string MaintenanceType { get; set; }

    public decimal? MaintenanceCost { get; set; }

    public string Notes { get; set; }

    public DateTime? NextMaintenanceDate { get; set; }

    public int? PricingRuleApplied { get; set; }

    public virtual StationHuyNd NewStation { get; set; }

    public virtual StationHuyNd PreviousStation { get; set; }

    public virtual PricingPhatNt PricingRuleAppliedNavigation { get; set; }

    public virtual VehicleHaLth Vehicle { get; set; }
}