// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class VehicleHaLth
{
    public int VehicleHaLthid { get; set; }

    public string VehicleModel { get; set; }

    public int BatteryCapacity { get; set; }

    public DateTime ManufacturingDate { get; set; }

    public bool IsAvailable { get; set; }

    public int CurrentStationId { get; set; }

    public string LicensePlate { get; set; }

    public string Color { get; set; }

    public DateTime? LastMaintenanceDate { get; set; }

    public string Status { get; set; }

    public decimal RentalPricePerHour { get; set; }

    public int MaxRange { get; set; }

    public int CurrentBatteryLevel { get; set; }

    public virtual ICollection<BookingCuongCla> BookingCuongClas { get; set; } = new List<BookingCuongCla>();

    public virtual StationHuyNd CurrentStation { get; set; }

    public virtual ICollection<RentalTransactionsKhanhLq> RentalTransactionsKhanhLqs { get; set; } = new List<RentalTransactionsKhanhLq>();

    public virtual ICollection<VehicleMaintenanceHistoryHaLth> VehicleMaintenanceHistoryHaLths { get; set; } = new List<VehicleMaintenanceHistoryHaLth>();

    public virtual ICollection<VehicleManagementPhatNt> VehicleManagementPhatNts { get; set; } = new List<VehicleManagementPhatNt>();
}