// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class VehicleMaintenanceHistoryHaLth
{
    public int VehicleMaintenanceHistoryHaLthid { get; set; }

    public int VehicleId { get; set; }

    public string MaintenanceType { get; set; }

    public DateTime MaintenanceDate { get; set; }

    public string Description { get; set; }

    public string PartsReplaced { get; set; }

    public decimal MaintenanceCost { get; set; }

    public string TechnicianName { get; set; }

    public decimal? BatteryHealthBefore { get; set; }

    public decimal? BatteryHealthAfter { get; set; }

    public string WarrantyStatus { get; set; }

    public int? CreatedBy { get; set; }

    public bool IsUnderWarranty { get; set; }

    public string Notes { get; set; }

    public virtual SystemUserAccount CreatedByNavigation { get; set; }

    public virtual VehicleHaLth Vehicle { get; set; }
}