// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zEVRental.Repositories.CuongCLA.Models;

public partial class ViolationRecordConglt
{
    public int ViolationCongltId { get; set; }

    public string ViolationType { get; set; }

    public string Description { get; set; }

    public byte SeverityLevel { get; set; }

    public decimal? PenaltyAmount { get; set; }

    public virtual ICollection<CustomerManagementConglt> CustomerManagementConglts { get; set; } = new List<CustomerManagementConglt>();
}